apiVersion: v1
kind: Secret
metadata:
  name: sql-optimization-agents-secrets
  namespace: default
type: Opaque
data:
  GOOGLE_API_KEY: eW91ci1nb29nbGUtYXBpLWtleQ==
  GOOGLE_APPLICATION_CREDENTIALS: eW91ci1nb29nbGUtYXBpLWtleQ==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-optimization-agents-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-optimization-agents
  template:
    metadata:
      labels:
        app: sql-optimization-agents
    spec:
      containers:
        - name: sql-optimization-agents
          image: us-central1-docker.pkg.dev/gd-gcp-rnd-analytical-platform/adp-rnd-gcp/sql-optimization-agents:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8880
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sql-optimization-agents-secrets
                  key: GOOGLE_API_KEY
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: sql-optimization-agents-secrets
                  key: GOOGLE_APPLICATION_CREDENTIALS
---
apiVersion: v1
kind: Service
metadata:
  name: sql-optimization-agents-service
  namespace: default
spec:
  selector:
    app: sql-optimization-agents
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8880
  type: ClusterIP
