name: Docker Image Build and Push to Google Artifact Registry
on:
  push:
    branches:
      - main # or your main branch
  workflow_dispatch: # Enables manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write' # Required for workload identity federation

    steps:
    - name: Check Secret Length
      run: echo "Length of GCP_CREDENTIALS"
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
    - name: List Environment Variables
      run: printenv

    - name: Checkout Repository
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        # workload_identity_provider: 'projects/117760548598/locations/global/workloadIdentityPools/terraform-identity-pool/providers/github-actions-oidc'
        # service_account: 'bq-optimization-lang-graph@gd-gcp-rnd-analytical-platform.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Configure Docker Authentication
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build Docker Image
      run: |
        docker build -t sql-optimization-agents:latest -f docker/Dockerfile .

    - name: Tag Docker Image
      run: |
        docker tag sql-optimization-agents:latest us-central1-docker.pkg.dev/gd-gcp-rnd-analytical-platform/adp-rnd-gcp/sql-optimization-agents:latest

    - name: Push Docker Image to Artifact Registry
      run: |
        docker push us-central1-docker.pkg.dev/gd-gcp-rnd-analytical-platform/adp-rnd-gcp/sql-optimization-agents:latest

    # - name: Deploy to Kubernetes (Optional - if desired)
    #   uses: appleboy/kubectl-action@v1.0.0
    #   with:
    #     kubeconfig: ${{ secrets.KUBE_CONFIG }} # Store your kubeconfig in GitHub secrets
    #     args: apply -f deployment.yaml # or your kubernetes deployment file.
